### ISSUE TITLE
帮忙看一个问题呢

### ISSUE THREAD

**Issue by TheFirstSunday** [liganghui/react-native-zhihuDaily#4]
F:\2018\zhihuDaily\android\app\src\debug\AndroidManifest.xml Warning:
        meta-data#android.support.FILE_PROVIDER_PATHS@android:resource was tagged at AndroidManifest.xml:0 to replace other declarations but no other declaration present

> Task :app:processDebugResources FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.5/userguide/command_line_interface.html#sec:command_line_warnings
277 actionable tasks: 5 executed, 272 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not read path 'F:\2018\zhihuDaily\android\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\androidx\core'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more det
ails.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not read path 'F:\2018\zhihuDaily\android\app\build\generated\not_namespaced_r_class_sources\debug\processDebugResources\r\androidx\core'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 37s

    at checkExecSyncError (child_process.js:621:11)
    at execFileSync (child_process.js:639:15)
    at runOnAllDevices (F:\2018\zhihuDaily\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:39)
    at buildAndRun (F:\2018\zhihuDaily\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:158:41)
    at F:\2018\zhihuDaily\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\index.js:125:12
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Command.handleAction (F:\2018\zhihuDaily\node_modules\@react-native-community\cli\build\index.js:164:9)

不知为何跑你这个项目跑不起来，还能帮忙看下什么问题。

**Comment by liganghui** [comment]
试试  cd android && ./gradlew clean  然后多试几次 react-native run-android

**Comment by liganghui** [comment]
顺便移除如图所示的两行代码  。 避免系统桌面两个APP图标的问题。
![QQ截图20191106180451](https://user-images.githubusercontent.com/15844198/68289144-97e04680-00c0-11ea-8733-85e22b653263.png)
